---
tools:
  bspsrc: "../../thirdparty/bspsrc/bspsrc.jar"
  pakrat: "../../thirdparty/pakrat/pakrat.jar"
  vtf2tga: "../../utilities/vtf2tga/vtf2tga"
do_maps: false
do_vpks: true
extract_paths:
  "maps/": "*.txt"
  "materials/overviews/": "*"
  "materials/vgui/gameui/": "*"
  "materials/vgui/hud/": "*"
  "materials/vgui/hud_doi/": "*"
  "materials/vgui/inventory/": "*"
  "materials/vgui/logos/": "*"
  "materials/vgui/maps/": "*"
  "resource/": "*.txt *.res"
  "scripts/playlists/": "*.txt"
  "scripts/theaters/": "*.theater"
extract_root: "../../data/mods"
game_roots:
  - "/home/doiserver/serverfiles"
  - "/home/insserver/serverfiles"
  - "~/serverfiles"
  - "~/Library/Application\ Support/Steam/steamapps/common"
games:
  "dayofinfamy":
    game_dir: "doi"
  "insurgency":
    game_name: "insurgency2"
    game_dir: "insurgency"
vpk_files:
  - "misc"
  - "materials"
...
