---
extract_root: "../../data/mods"
modules:
  cvarlist:
    enabled: true
    extract_paths:
    files_path: cvarlist
    files:
      - server.csv
      - client.csv
  maps:
    enabled: false
    extract_paths:
      "maps/": "*.txt"
  materials:
    enabled: true
    extract_paths:
      "materials/overviews/": "*"
      "materials/vgui/gameui/": "*"
      "materials/vgui/hud/": "*"
      "materials/vgui/hud_doi/": "*"
      "materials/vgui/inventory/": "*"
      "materials/vgui/logos/": "*"
      "materials/vgui/maps/": "*"
  models:
    enabled: false
    extract_paths:
  resource:
    enabled: true
    extract_paths:
      "resource/": "*.txt *.res"
  scripts:
    enabled: true
    extract_paths:
      "scripts/playlists/": "*.playlist"
      "scripts/theaters/": "*.theater"
  sourcemod:
    enabled: true
    extract_paths:
    files_path: sourcemod
    files:
      - classes.txt
      - datamaps.txt
      - netprops.txt
      - netprops.xml
  vpks:
    enabled: true
    extract_paths:
extract_paths:
      "maps/": "*.txt"
      "materials/overviews/": "*"
      "materials/vgui/gameui/": "*"
      "materials/vgui/hud/": "*"
      "materials/vgui/hud_doi/": "*"
      "materials/vgui/inventory/": "*"
      "materials/vgui/logos/": "*"
      "materials/vgui/maps/": "*"
      "resource/": "*.txt *.res"
      "scripts/playlists/": "*.playlist"
      "scripts/theaters/": "*.theater"
game_roots:
  - "/home/doiserver/serverfiles"
  - "/home/insserver/serverfiles"
  - "~/serverfiles"
  - "~/Library/Application\ Support/Steam/steamapps/common"
games:
  "dayofinfamy":
    game_dir: "doi"
  "insurgency":
    game_name: "insurgency2"
    game_dir: "insurgency"
map_files:
  bsp:
    "path": "maps"
    "match": "%(name)s.bsp"
  cpsetup_txt:
    "path": "maps"
    "match": "%(name)s.txt"
  json:
    "type": "output"
    "path": "maps/parsed"
    "match": "%(name)s.json"
  nav:
    "path": "maps"
    "match": "%(name)s.nav"
  overlay:
    "path": "maps/overlays"
    "match": "%(name)s.json"
  overview_png:
    "path": "materials/overviews"
    "match": "%(name)s.png"
  overview_txt:
    "path": "resource/overviews"
    "match": "%(name)s.txt"
  overview_vmt:
    "path": "materials/overviews"
    "match": "%(name)s.vmt"
  overview_vtf:
    "path": "materials/overviews"
    "match": "%(name)s.vtf"
  vmf:
    "path": "maps/src"
    "match": "%(name)s_d.vmf"
map_entities:
  "ins_blockzone": {}
  "ins_spawnzone": {}
  "obj_weapon_cache": {}
  "point_controlpoint": {}
  "trigger_capture_zone": {}
map_entities_props:
  "angles":
    type: vertex
  "blockzone":
    type: entity
  "classname": {}
  "model": {}
  "origin":
    type: vertex
  "printname":
    type: translate
  "skin": {}
  "spawnflags": {}
  "SquadID": {}
  "StartDisabled": {}
  "targetname":
    type: name
  "TeamNum": {}
tools:
  bspsrc: "../../thirdparty/bspsrc/bspsrc.jar"
  pakrat: "../../thirdparty/pakrat/pakrat.jar"
  vtf2tga: "../../utilities/vtf2tga/vtf2tga"
vpk_files:
  - "misc"
  - "materials"
...
