#!/bin/bash
#FILE=$(readlink -f $0)
#LIBDIR=$(cd $(dirname $FILE)/../lib && pwd)
#LD_LIBRARY_PATH=$LIBDIR cd $PWD && ${FILE}_linux32 $@

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
LIBDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../lib" && pwd )"
export LD_LIBRARY_PATH=$LIBDIR
exec "$DIR/vpk_linux32" "$@"
